package com.tweetapp.models;

import java.util.Date;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "tweetReply")
public class TweetReply {

	private String id;

	@NotBlank
	@Size(max = 20)
	private String repliedby;

	@NotBlank
	// @Size(max = 20)
	private Date datetime;

	@NotBlank
	private String tweetId;

	@NotBlank
	@Size(max = 144)
	private String reply;

	public TweetReply(@NotBlank @Size(max = 20) String repliedby, @NotBlank Date datetime,
			@NotBlank String tweetId, @NotBlank @Size(max = 144) String reply) {
		super();
		this.repliedby = repliedby;
		this.datetime = datetime;
		this.tweetId = tweetId;
		this.reply = reply;
	}

	public TweetReply() {
		super();
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute
	public String getRepliedby() {
		return repliedby;
	}

	public void setRepliedby(String repliedby) {
		this.repliedby = repliedby;
	}

	@DynamoDBAttribute
	public Date getDatetime() {
		return datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	@DynamoDBAttribute
	public String getTweetId() {
		return tweetId;
	}

	public void setTweetId(String tweetId) {
		this.tweetId = tweetId;
	}

	@DynamoDBAttribute
	public String getReply() {
		return reply;
	}

	public void setReply(String reply) {
		this.reply = reply;
	}

}
