version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tweetapp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6woumfea9ojo"
s3_prefix = "tweetapp"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
